devsearch/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('projects/',include('projects.urls')),
    path('',include('users.urls'))
]

urlpatterns += static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root= settings.STATIC_ROOT)

users/urls.py
from django.urls import path, include
from .views import profiles, registerUser,user_profile, loginPage, logoutPage

urlpatterns = [
    
    path('',profiles,name="profiles"),
    path('login/', loginPage, name="login"),
    path('logout/', logoutPage, name="logout"),
    path('register/', registerUser, name="register"),
    path('user_profile/<str:pk>/',user_profile, name="user_profile")
]

projects/models.py
from django.db import models
import uuid
from users.models import Profile

class Project(models.Model):
    
    owner = models.ForeignKey(Profile, null=True, blank=True, on_delete=models.SET_NULL)
    title = models.CharField(max_length=200)
    description = models.TextField(null=True, blank=True)
    tags = models.ManyToManyField('Tag',blank=True)
    featured_image = models.ImageField(null=True, blank=True, default="default.jpg")
    demo_link = models.CharField(max_length=200,null=True, blank=True)
    source_link = models.CharField(max_length=200,null=True, blank=True)
    vote_total = models.IntegerField(default=0,null=True,blank=True)
    vote_ratio = models.IntegerField(default=0,null=True,blank=True)
    created = models.DateTimeField(auto_now_add=True)
    id = models.UUIDField(default=uuid.uuid4, unique=True, primary_key=True, editable=False)

    def __str__(self):
        return self.title

class Review(models.Model):

    VOTE_TYPE = (
        ('up','Up Vote'),
        ('down','Down Vote'),
    )
    #owner=
    project = models.ForeignKey(Project,on_delete=models.CASCADE)
    body = models.TextField(null=True, blank=True)
    value = models.CharField(max_length=200,choices=VOTE_TYPE)
    created = models.DateTimeField(auto_now_add=True)
    id = models.UUIDField(default=uuid.uuid4, unique=True, primary_key=True, editable=False)

    def __str__(self):
        return self.value

class Tag(models.Model):
    name = models.CharField(max_length=200)
    created = models.DateTimeField(auto_now_add=True)
    id = models.UUIDField(default=uuid.uuid4, unique=True, primary_key=True, editable=False)

    def __str__(self):
        return self.name

users/models.py
from django.db import models
from django.contrib.auth.models import User
import uuid

class Profile(models.Model):
    user = models.OneToOneField(
        User, on_delete=models.CASCADE, null=True, blank=True)
    name = models.CharField(max_length=200, blank=True, null=True)
    email = models.EmailField(max_length=500, blank=True, null=True)
    username = models.CharField(max_length=200, blank=True, null=True)
    location = models.CharField(max_length=200, blank=True, null=True)
    short_intro = models.CharField(max_length=200, blank=True, null=True)
    bio = models.TextField(blank=True, null=True)
    profile_image = models.ImageField(
        null=True, blank=True, upload_to='profiles/', default="profiles/user-default.png")
    social_github = models.CharField(max_length=200, blank=True, null=True)
    social_twitter = models.CharField(max_length=200, blank=True, null=True)
    social_linkedin = models.CharField(max_length=200, blank=True, null=True)
    social_youtube = models.CharField(max_length=200, blank=True, null=True)
    social_website = models.CharField(max_length=200, blank=True, null=True)
    created = models.DateTimeField(auto_now_add=True)
    id = models.UUIDField(default=uuid.uuid4, unique=True,
                          primary_key=True, editable=False)

    def __str__(self):
        return str(self.username)

class Skill(models.Model):
    owner = models.ForeignKey(Profile, on_delete=models.CASCADE, null=True, blank=True)
    name = models.CharField(max_length=200,null=True, blank=True)
    description = models.TextField(null=True, blank=True)
    created = models.DateTimeField(auto_now_add=True)
    id = models.UUIDField(default=uuid.uuid4, unique=True,
                          primary_key=True, editable=False)

    def __str__(self):
        return str(self.name)

users/forms.py
from django.forms import ModelForm
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['first_name', 'email', 'username', 'password1', 'password2']
        labels = {
            'first_name': 'Name',
        }

      
             
             

                

users/views.py
from django.shortcuts import render, redirect
from .models import Profile
from django.contrib.auth.models import User
from django.contrib.auth import login, authenticate, logout
from django.contrib import messages
from .forms import CustomUserCreationForm

def loginPage(request):
    page='login'
    if request.user.is_authenticated:
        return redirect('profiles')
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']

        try :
            user = User.ojects.get(username=username)
        except:
            messages.error(request, 'user does not exist ')
        
        user = authenticate(request, username=username, password=password)

        if user is not None:
            login(request, user)
            return redirect('profiles')
        else:
            messages.error(request, 'user/password didnt match')
            return render(request,'users/login_register.html')
    return render(request,'users/login_register.html')

def registerUser(request):
    page='register'
    form = CustomUserCreationForm()
    
    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.username = user.username.lower()
            user.save()
            messages.success(request, "User accont was created")
            login(request, user)
            return redirect('profiles')
        else:
            messages.error(request, "Error has occurred.")

    context = {'page':page,'form':form}
    return render(request, 'users/login_register.html',context)

def logoutPage(request):
    logout(request)
    return redirect('login')

def profiles(request):
    profile = Profile.objects.all()
    context = {'profiles':profile}
    return render(request, 'users/profile.html',context)

def user_profile(request,pk):
    profile = Profile.objects.get(id=pk)
    print("PROFILE",profile)
    top_skills = profile.skill_set.exclude(description__exact="")
    other_skills = profile.skill_set.filter(description__exact="")

    context = {
        'profile':profile,
        'top_skills':top_skills,
        'other_skills':other_skills
    }
    return render(request, "users/user_profile.html",context)

users/templates/users/login_register.html
{% extends 'base.html' %}
{% block content %}

{% load static %}

{% if page == 'register' %}

<div class="auth">
    <div class="card">
      <div class="auth__header text-center">
        <a href="/">
          <img src="{% static 'images/icon.svg' %}" alt="icon" />
        </a>
        <h3>Register Here</h3>
        <p>Create a new developer account</p>
      </div>

      <form action="{% url 'register'%}" method="post" class="form auth__form">
        <!-- Input:Text -->
        {% csrf_token %}
        {%for field in form%}
        <div class="form__field">
            <label for="formInput#text">{{field.label}} </label>
            {{field}}

            {% for error in field.errors%}
                <p style="color: red;">{{error}}</p>
            {% endfor %}
          </div>
        {%endfor%}
        
        <div class="auth__actions">
          <input class="btn btn--sub btn--lg" type="submit" value="Sign  In" />
        </div>
      </form>
      <div class="auth__alternative">
        <p>Already have an Account?</p>
        <a href="{% url 'login'%}">Log In</a>
      </div>
    </div>
  </div>
{% else %}



<div class="auth">
    <div class="card">
      <div class="auth__header text-center">
        <a href="/">
          <img src="{% static 'images/icon.svg' %}" alt="icon" />
        </a>
        <h3>Account Login</h3>
        <p>Hello Developer, Welcome Back!</p>
      </div>

      <form action="{% url 'login' %}" method="post" class="form auth__form">
        <!-- Input:Username -->
        {% csrf_token %}
        <div class="form__field">
          <label for="formInput#text">Username: </label>
          <input
            class="input input--text"
            id="formInput#text"
            type="text"
            name="username"
            placeholder="Enter your username..."
          />
        </div>

        <!-- Input:Password -->
        <div class="form__field">
          <label for="formInput#password">Password: </label>
          <input
            class="input input--password"
            id="formInput#passowrd"
            type="password"
            name="password"
            placeholder="••••••••"
          />
        </div>
        <div class="auth__actions">
          <input class="btn btn--sub btn--lg" type="submit" value="Log In" />
          <a href="forgetpassword.html">Forget Password?</a>
        </div>
      </form>
      <div class="auth__alternative">
        <p>Don’t have an Account?</p>
        <a href="{% url 'register'%}">Sign Up</a>
      </div>
    </div>
  </div>
{% endif %}



{% endblock %}

users/templates/users/profile.html
{% extends 'base.html'%}

{% block content %}

 <!-- Main Section -->
 <main class="home">
    <section class="hero-section text-center">
      <div class="container container--narrow">
        <div class="hero-section__box">
          <h2>CONNECT WITH <span>DEVELOPERS</span></h2>
          <h2>FROM AROUND THE WORLD</h2>
        </div>

        <div class="hero-section__search">
          <form class="form" action="#" method="get">
            <div class="form__field">
              <label for="formInput#search">Search Developers </label>
              <input class="input input--text" id="formInput#search" type="text" name="text"
                placeholder="Search by developer name" />
            </div>

            <input class="btn btn--sub btn--lg" type="submit" value="Search" />
          </form>
        </div>
      </div>
    </section>
    <!-- Search Result: DevList -->
    <section class="devlist">
      <div class="container">
        <div class="grid grid--three">
          {% for profile in profiles%}
          <div class="column card">
            <div class="dev">
              <a href="{% url 'user_profile' profile.id %}" class="card__body">
                <div class="dev__profile">
                  <img class="avatar avatar--md" src="{{profile.profile_image.url}}" alt="image" />
                  <div class="dev__meta">
                    <h3>{{profile.name}}</h3>
                    <h5>{{profile.short_intro}}</h5>
                  </div>
                </div>
                <p class="dev__info">
                  {{profile.bio|slice:"150"}}
                </p>
                <div class="dev__skills">
                  {% for skill in profile.skill_set.all %}
                  <span class="tag tag--pill tag--main">
                    <small>{{skill}}</small>
                  </span>
                  {% endfor %}
                 
                </div>
              </a>
            </div>
          </div>
          {% endfor %}
        
        </div>
      </div>
    </section>

  </main>

{% endblock %}

users/templates/users/user_profile.html
{% extends 'base.html' %}
{% block content %}

<!-- Main Section -->
<main class="profile my-md">
    <div class="container">
      <div class="layout">
        <div class="column column--1of3">
          <div class="card text-center">
            <div class="card__body dev">
              <img class="avatar avatar--xl" src="{{profile.profile_image.url}}" />
              <h2 class="dev__name">{{profile.name}}</h2>
              <p class="dev__title">{{profile.short_intro}}</p>
              <p class="dev__location">Based in {{profile.location}}</p>
              <ul class="dev__social">
                <li>
                  <a title="Github" href="{{profile.social_github}}" target="_blank"><i class="im im-github"></i></a>
                </li>
                <li>
                  <a title="Stackoverflow" href="{{profile.social_github}}" target="_blank"><i class="im im-stackoverflow"></i></a>
                </li>
                <li>
                  <a title="Twitter" href="{{profile.social_github}}" target="_blank"><i class="im im-twitter"></i></a>
                </li>
                <li>
                  <a title="LinkedIn" href="{{profile.social_github}}" target="_blank"><i class="im im-linkedin"></i></a>
                </li>
                <li>
                  <a title="Personal Website" href="{{profile.social_github}}" target="_blank"><i class="im im-globe"></i></a>
                </li>
              </ul>
              <a href="#" class="btn btn--sub btn--lg">Send Message </a>
            </div>
          </div>
        </div>
        <div class="column column--2of3">
          <div class="devInfo">
            <h3 class="devInfo__title">About Me</h3>
            <p class="devInfo__about">
              {{profile.bio}}
              <br />
              
            </p>
          </div>
          
          <div class="devInfo">
            <h3 class="devInfo__title">Skills</h3>
           {% for skill in top_skills %}
            <div class="devInfo__skills">
              <div class="devSkill">
                <h4 class="devSkill__title">{{skill.name}}</h4>
                <p class="devSkill__info">
                  {{skill.description}}
                </p>
              </div>
              {% endfor %}

              <h3 class="devInfo__subtitle">Other Skills</h3>
              <div class="devInfo__otherSkills">
                {% for skill in other_skills %}
                <span class="tag tag--pill tag--sub tag--lg">
                  <small>Figma</small>
                </span>
                {% endfor %}
               
              </div>
            </div>
          </div>
          <div class="devInfo">
            <h3 class="devInfo__title">Projects</h3>
            <div class="grid grid--two">

              {% for profile in profile.project_set.all %}
              <div class="column">
                <div class="card project">
                  <a href="{% url 'single_project' profile.id %}" class="project">
                    <img class="project__thumbnail" src="{{profile.featured_image.url}}" alt="project thumbnail" />
                    <div class="card__body">
                      <h3 class="project__title">{{profile.title}}</h3>
                      <p><a class="project__author" href="{% url 'user_profile' profile.owner.id %}">{{profile.owner}}</a></p>
                      <p class="project--rating">
                        <span style="font-weight: bold;">{{profile.vote_ratio}}%</span> Postitive
                        Feedback {{project.vote_total}} Vote{{project.vote_total | pluralize:'s'}}
                      </p>
                      <div class="project__tags">
                        {% for tag in project.tags.all %}
                        <span class="tag tag--pill tag--main">
                          <small>{{tag}}</small>
                        </span>
                        {% endfor %}
                      </div>
                    </div>
                  </a>
                </div>
              </div>
              {% endfor %}
       

              

            </div>
          </div>
        </div>
      </div>
    </div>
  </main>

{% endblock %}